name: Build and Release v1.1.0

on:
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest # you cannot escape canonical

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Create and push tag v1.1.0
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -fa v1.1.0 -m "Tag version v1.1.0"
          git push origin --force v1.1.0
          
      - name: Set up Arch container and build package
        uses: addnab/docker-run-action@v3
        id: build
        with:
          image: archlinux:latest
          options: -v ${{ github.workspace }}:/repo --rm
          run: |
            pacman -Sy --noconfirm base-devel
            useradd -m builder
            echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder
            chown -R builder:builder /repo
            sudo -u builder bash -c "cd /repo && makepkg --noconfirm -s"

            pkg=$(find /repo -maxdepth 1 -type f -name "*.pkg.tar.zst" | head -n 1)
            echo "$pkg" >> /repo/package_path.txt
            echo "$(basename "$pkg")" >> /repo/package_name.txt

      - name: Read package path and name
        id: get_path
        run: |
          echo "package_path=$(cat /repo/package_path.txt)" >> $GITHUB_OUTPUT
          echo "package_name=$(cat /repo/package_name.txt)" >> $GITHUB_OUTPUT
      
      - name: Create GitHub release 1.1.0
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.1.0
          release_name: Version 1.1.0
          body: |
            archapt is basically complete now. cool, huh?
            there are still some additions that could be made, but for the most part, its good.
            also this github actions workflow was so hard to make
            peace out, enjoy archapt fellas
            - spark
          draft: false
          prerelease: false

      - name: Upload built package
        ## uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ## with:
          ## upload_url: ${{ steps.create_release_outputs.upload_url }}
          ## asset_path: ${{ steps.build.outputs.package_path }}
          ## asset_name: $(basename ${{ steps.build.outputs.package_name }})
          ## asset_content_type: application/octet-stream
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.get_path.outputs.package_path }}

# done
