name: Build and Release v1.1.0

on:
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest # you cannot escape canonical

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Arch container and build package
        uses: addnab/docker-run-action@v3
        id: build
        with:
          image: archlinux:latest
          options: -v ${{ github.workspace }}:/repo --rm
          run: |
            pacman -Sy --noconfirm base-devel git
            useradd -m builder
            echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder
            chown -R builder:builder /repo
            sudo -u builder bash -c "cd /repo && makepkg --noconfirm -s"

            pkg=$(find /repo -maxdepth 1 -type f -name "*.pkg.tar.zst" | head -n 1)
            echo "::set-output name=package::$pkg"

      - name: Create GitHub release 1.1.0
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-name: v1.1.0
          release-name: Version 1.1.0
          body: archapt is basically complete now. cool, huh? there are still some additions that could be made, but for the most part, its good
          draft: false
          prerelease: false

      - name: Upload built package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.package }}
          asset_name: $(basename ${{ steps.build.outputs.package }})
          asset_content_type: application/octet-stream

# done
